islandsWorldName: world
wildernessWorldName: wilderness

defaultIslandLimit: 2
groupLimits:                            # Requires vault to work, all limits can be bypassed with islands.bypass.islandLimit
  staff: 5

islandSizes:                            # Island sizing. You can add or remove as many sizes as you want.
  BIG: 80                               # NORMAL is the fallback size. At least 1 size has to be defined.
  NORMAL: 64                            # For now due to bukkit api, the default sizes here can be disabled only by
  SMALL: 32                             # setting their size as 0.

islandPrices:                           # If vault has been enabled, you can set island creation prices here
  BIG: 5000
  NORMAL: 3000
  SMALL: 1000

economy:
  recreateCost: 0                       # Will be added to island prices when recreating island
  recreateSum: true                     # When enabled, recreate price will be newIslandPrice - oldIslandPrice and > 0.

replaceOnGeneration:                    # Replace blocks when generating new island. Format: toReplace: replaceWith
  iron_ore: stone
  gold_ore: stone
  coal_ore: stone
  gravel: stone

generation:
  searchJump: 6                         # How man blocks should be skipped when looking for biomes, bigger faster
  biomeSearchArea: 3500                 # Biome search area, smaller faster. Increase this if you want more biomes to be available.
  islandGridSpacing: 100                # At least the size of island.BIG + 4. Space between island centres.
  islandGridVerticalSpacing: 50         # Vertical space between two islands next to each other.
  generationDelayInTicks: 0.3           # 2 Will generate 1 row per 2 ticks, 0.5 will generate 2 rows per 1 tick.
  maxVariationsPerBiome: 5              # Max locations generated for each biome, lower the value to speed up server startup.
  clearSpeedMultiplier: 3               # Removing blocks should be faster than placing them, so you might swant to speed up clearing.

biomeBlacklist:                         # These biomes do not get picked up by island generator.
  - DEEP_OCEAN                          # Ocean biomes work poorly with islands.
  - DEEP_WARM_OCEAN
  - DEEP_LUKEWARM_OCEAN
  - DEEP_COLD_OCEAN
  - DEEP_FROZEN_OCEAN
  - SHATTERED_SAVANNA
  - SHATTERED_SAVANNA_PLATEAU
  - MOUNTAINS
  - GRAVELLY_MOUNTAINS
  - MODIFIED_GRAVELLY_MOUNTAINS

disableMobsOnIslands: true
tpCooldownTime: 10                      # /home and /visit cooldown after damage.
illegalIslandNames:                     # Blocked island names. Useful if you want to reserve name for "official" island
#  - spawn
wildernessCoordinateMultiplier: 4       # Player's x and z coordinates gets multiplied by this value when they jump to wilderness.
locale: en
