defaultIslandLimit: 2
groupLimits:                  # Requires vault to work, all limits can be bypassed with islands.bypass.islandLimit
  staff: 5

islandSizes:                            # Island sizing. You can add as many sizes as you want.
  BIG: 80                               # NORMAL is the fallback size. At least 1 size has to be defined.
  NORMAL: 64
  SMALL: 32

islandShapes:                           # Island shapes. Shapes are located in plugins/Islands/shapes/
  - shape_small                         # File name without .schem or .schematic extension. For example, this shape has
                                        # width of 32, so it will be used for all islands that are 32x32.

replaceOnGeneration:                    # Replace blocks when generating new island. Format: toReplace: replaceWith
  iron_ore: stone
  gold_ore: stone
  coal_ore: stone

generation:
  searchJump: 8                         # How man blocks should be skipped when looking for biomes, bigger faster
  biomeSearchArea: 3500                 # Biome search area, smaller faster. Increase to make more biomes available.
  islandGridSpacing: 100                # At least the size of island.BIG + 4
  islandGridVerticalSpacing: 50
  generationDelayInTicks: 0.3           # 2 Will generate 1 row per 2 ticks, 0.5 will generate 2 rows per 1 tick
  maxVariationsPerBiome: 3              # Max locations generated for each biome, lower the value to speed up server startup.

disableMobsOnIslands: true
tpCooldownTime: 10                      # /home and /visit cooldown after damage.
illegalIslandNames:                     # Blocked island names.
#  - spawn
biomeBlacklist:                         # These biomes do not get picked up by island generator
  - DEEP_OCEAN
  - DEEP_WARM_OCEAN
  - DEEP_LUKEWARM_OCEAN
  - DEEP_COLD_OCEAN
  - DEEP_FROZEN_OCEAN
  - SHATTERED_SAVANNA
  - SHATTERED_SAVANNA_PLATEAU
  - MOUNTAINS
  - GRAVELLY_MOUNTAINS
  - MODIFIED_GRAVELLY_MOUNTAINS
wildernessCoordinateMultiplier: 4       # Player's x and z coordinates gets multiplied with this value when they jump to wilderness.
islandsWorldName: world
wildernessWorldName: wilderness
