defaultIslandLimit: 2
groupLimits:                  # Requires vault to work, all limits can be bypassed with islands.bypass.islandLimit
  staff: 5

island:                       # Island sizing
  BIG: 80
  NORMAL: 64
  SMALL: 32

generation:
  searchJump: 8                         # How man blocks should be skipped when looking for biomes, bigger faster
  searchArea: 1000                      # Biome search area, smaller faster
  islandsInARow: 4
  islandSpacing: 100                    # At least the size of island.BIG
  islandVerticalSpacing: 50
  generationDelayInTicks: 1             # 2 Will generate 1 row per 2 ticks, 0.5 will generate 2 rows per 1 tick
  maxVariationsPerBiome: 5

disableMobsOnIslands: true
tpCooldownTime: 10                      # /home and /visit cooldown after damage.
# Blocked island names.
illegalIslandNames:
# - spawn
