name: Islands
version: 0.0.1
author: Aleksi Lassila
main: me.aleksilassila.islands.Main
api-version: 1.16
commands:
  go:
    description: Your description
    usage: /<command>
    permission: yourplugin.yourcommandpermission
  island:
    description: Your description
    usage: /<command> biome
    permission: yourplugin.yourcommandpermi
    aliases: [is]
  visit:
    description: Your description
    usage: /<command> biome
    permission: yourplugin.yourcommandpermi
    aliases: [vi]