name: Islands
version: 4.0.0
author: Aleksi Lassila
main: me.aleksilassila.islands.Main
api-version: 1.15
softdepend: [Vault, WorldEdit]
commands:
  island:
    description: Island managment
    usage: /<command>
    aliases: [is]
  visit:
    description: Visit islands
    usage: /<command> name
    aliases: [vi]
  home:
    description: Teleport to your home island
    usage: /<command> ([home id])
  homes:
    description: List homes
    usage: /<command>
  trust:
    description: Trust a player
    usage: /<command> player
  trusted:
    description: List trusted players
    usage: /<command>
  untrust:
    description: Untrust a player
    usage: /<command> player
