name: Islands
version: 0.0.1
author: Aleksi Lassila
main: me.aleksilassila.islands.Main
api-version: 1.16
commands:
  go:
    description: Your description
    usage: /<command>
    permission: yourplugin.yourcommandpermission
  island:
    description: Your description
    usage: /<command> biome
    permission: yourplugin.yourcommandpermi
    aliases: [is]
  visit:
    description: Your description
    usage: /<command> name
    permission: yourplugin.yourcommandpermi
    aliases: [vi]
  home:
    description: Teleport to your home island
    usage: /<command> [home id]
    permission: yourplugin.yourcommandpermi
  homes:
    description: List homes
    usage: /<command>
    permission: yourplugin.yourcommandpermi
  trust:
    description: Trust a player
    usage: /<command>
    permission: yourplugin.yourcommandpermi
  untrust:
    description: Untrust a player
    usage: /<command>
    permission: yourplugin.yourcommandpermi