name: Islands
version: 0.0.1
author: Aleksi Lassila
main: me.aleksilassila.islands.Islands
api-version: 1.16
commands:
  go:
    description: Your description
    usage: /<command>
    permission: yourplugin.yourcommandpermission
  findisland:
    description: Your description
    usage: /<command> biome
    permission: yourplugin.yourcommandpermi
  createisland:
    description: Your description
    usage: /<command>
    permission: yourplugin.yourcommandpermi